### ISSUE TITLE
Compiler errors with newer version of ESP-IDF

### ISSUE THREAD

**Issue by qanh96** [shmuelzon/esp32-ble2mqtt#34]
Hello and many thanks for this quality project
With the slight older ESP-IDF from Espressif everything work fine, but i'm having compiler Errors with the newer version when try to build a new clone of the project
Ich have already tried things like fresh installation of IDF or fresh clone of project and confirmed the same problems on multiple devices.

Thanks for your hardwork!

`CC build/lwip/port/esp32/debug/lwip_debug.o
AR build/lwip/liblwip.a
CC build/main/broadcasters.o
In file included from C:/msys32/home/esp/esp32-ble2mqtt/main/broadcasters.c:8:0:
C:/msys32/home/esp/esp32-ble2mqtt/main/broadcasters.c: In function 'ibeacon_is_b                                                     roadcaster':
C:/msys32/home/esp/esp-idf/components/wpa_supplicant/port/include/endian.h:78:20                                                     : error: implicit declaration of function '__bswap16' [-Werror=implicit-function                                                     -declaration]
 #define bswap16(x) __bswap16(x)
                    ^
C:/msys32/home/esp/esp-idf/components/wpa_supplicant/port/include/endian.h:116:2                                                     0: note: in expansion of macro 'bswap16'
 #define le16toh(x) bswap16((x))
                    ^
C:/msys32/home/esp/esp32-ble2mqtt/main/broadcasters.c:85:12: note: in expansion                                                      of macro 'le16toh'
     return le16toh(beacon->company_id) == 0x004C /* Apple */ &&
            ^
C:/msys32/home/esp/esp32-ble2mqtt/main/broadcasters.c: At top level:
cc1.exe: warning: unrecognized command line option '-Wno-frame-address'
cc1.exe: some warnings being treated as errors
make[1]: *** [/home/esp/esp-idf/make/component_wrapper.mk:290: broadcasters.o] F                                                     ehler 1
make: *** [C:/msys32/home/esp/esp-idf/make/project.mk:582: component-main-build]                                                      Fehler 2
`

**Comment by shmuelzon** [comment]
Hey,

It seems that commit https://github.com/espressif/esp-idf/commit/d15e18aa5db53f55344bbb4a7623d3dd46b6ad0f (changes done on components/wpa_supplicant/port/include/endian.h) is what broke things. It removed the defines needed to actually map the endianess conversion functions to something useful.
You could apply the following patch and the project should compile:
```patch
diff --git a/main/ble_utils.h b/main/ble_utils.h
index 6c6c181..88b1d03 100644
--- a/main/ble_utils.h
+++ b/main/ble_utils.h
@@ -4,6 +4,10 @@
 #include <esp_gap_ble_api.h>
 #include <esp_gattc_api.h>
 
+#define __bswap16     __bswap_16
+#define __bswap32     __bswap_32
+#define __bswap64     __bswap_64
+
 #define MAC_FMT "%02x:%02x:%02x:%02x:%02x:%02x"
 #define MAC_PARAM(mac) mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]
 
```
I, generally, try to stay on official releases so these kinds of things won't happen. Currently, as is described in the README file, I'm working against ESP-IDF v3.2 and that's what I can really support.
I've seen unstable versions come with all sorts of weird behavior and stability problems.

Out of curiosity, do you have any reason to use ESP-IDF's top-of-branch instead of the latest release?

Good day!

**Comment by qanh96** [comment]
Thank you for your help, i will stick to the stable v3.2 to build the project.

As for reson to use the lastest Version, we want to try out the some of the new functions that supposed to give us more control to the energie consumption of the ESP32 and see how can we create sth that consume as little energie as possible. 

Thanks again for this well made and active supported Projects
Best regard!
